name: Run Playwright Autotests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

         # Step 2: Checkout the Playwright tests repository (your 'play' repo)
      - name: Checkout the Playwright test repository
        uses: actions/checkout@v4
        with:
          repository: Inna-test/play  # This is the repository with the 'tests' directory
          token: ${{ secrets.AUTOTEST_REPO_TOKEN }}  # GitHub secret with access to 'play' repo
          path: play  # You can specify a folder name (e.g., 'play') where the tests will be saved

      - name: Install dependencies
        run: |
          npm install

      - name: Start Next.js app in the background
        run: |
          nohup npm run dev &  # Start Next.js app in the background

    # Set up Python environment for Playwright
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use any Python version that supports Playwright

    # Install dependencies for the Playwright tests
      - name: Install test dependencies
        run: |
          cd tests
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          playwright install

    # Step 8: Install Python dependencies for Playwright
      - name: Install Python dependencies
        run: |
          pip install -r play/tests/requirements.txt  # Install dependencies from the 'play/tests' folder

      # Step 9: Run Playwright tests
      - name: Run Playwright tests
        run: |
          pytest play/tests  # Run Playwright tests located in 'play/tests' folder
