name: Run Playwright Autotests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Start Next.js app in the background
        run: |
          nohup npm run dev &  # Start Next.js app in the background

    # Set up Python environment for Playwright
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use any Python version that supports Playwright

    # Install dependencies for the Playwright tests
      - name: Install test dependencies
        run: |
          cd tests
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          playwright install

    # Run Playwright tests using pytest
      - name: Run Playwright tests
        run: |
          cd tests
          pytest  # Run the tests using pytest
        ##
