name: Run Playwright Autotests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this (Next.js) repo
      uses: actions/checkout@v4

    - name: Checkout the test repo
      uses: actions/checkout@v4
      with:
        repository: Inna-test/testplaywright
        token: ${{ secrets.AUTOTEST_REPO_TOKEN }}
        path: tests

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install test dependencies
      run: |
        cd tests
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Playwright tests
      run: |
        cd tests
        pytest